"""empty message

Revision ID: 86294979f0b5
Revises: 3543fadfb77e
Create Date: 2021-06-01 12:47:26.555539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86294979f0b5'
down_revision = '3543fadfb77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('url_to', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'url_to')
    # ### end Alembic commands ###
